@echo off
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\bc56\test\vc6\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\cw8\test\vc6\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\dmbeta\test\vc6\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\gcc32\test\vc6\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\icl7\test\vc6\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\bc56\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\cw8\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\dmbeta\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\gcc32\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\icl7\cdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cdynamic_test\vc6\test\vc6\cdynamic_test.exe
