//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sketch.rc
//
#define ID_OPTIONS_CLEAR                40001
#define ID_OPTIONS_EXIT                 40002
#define ID_PEN_TWO                      40004
#define ID_PEN_FIVE                     40005
#define ID_PEN_TEN                      40006
#define ID_PEN_THIRTY                   40007
#define ID_PEN_SIXTY                    40008
#define ID_HELP_ABOUT                   40009
#define ID_OPTIONS_COLORS               40010
#define IDM_BLACK                       40011
#define IDM_WHITE                       40012
#define IDM_RED                         40013
#define IDM_GREEN                       40014
#define IDM_BLUE                        40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
