# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

mem_access_bug:
	gcc -Wall -o mem_access_bug -g mem_access_bug.c

clean:
	rm -rf $(CLEAN_TARGETS) mem_access_bug
