//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Fourier.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FOURIETYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_RADIO1                      1002
#define IDC_RADIO2                      1003
#define IDC_RADIO3                      1004
#define IDM_FOURIER                     32771
#define IDM_COLOR                       32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
