# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

static_conflict:
	g++ -Wall -o static_conflict -g static_conflict.cc MyClass.cc

clean:
	rm -rf $(CLEAN_TARGETS) static_conflict
