# Makefile.include Copyright 2008 Groetker, Holtmann, Keding, Wloka

# common settings to include 

# clean

CLEAN_TARGETS = $(CLEAN_TARGETS_LINUX) $(CLEAN_TARGETS_WINDOWS) $(CLEAN_TARGETS_EDIT)

CLEAN_TARGETS_LINUX = *.exe *.o *.stackdump

CLEAN_TARGETS_WINDOWS = \
    *.exe *.obj \
    vc8/*.ncb vc8/*.suo vc8/*.user \
    vc8/Debug \
    vc8/Release \
    vc9/*.ncb vc9/*.suo vc9/*.user \
    vc9/Debug \
    vc9/Release

CLEAN_TARGETS_EDIT = *~ *.bak
