

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::MemoryTest::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'messageArea'
    messageArea = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"messageArea"));
    // Get the Grid named 'cardGrid'
    cardGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cardGrid"));
    // Get the RichTextBlock named 'winMessage'
    winMessage = safe_cast<::Windows::UI::Xaml::Controls::RichTextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"winMessage"));
    // Get the RichTextBlock named 'playMessage'
    playMessage = safe_cast<::Windows::UI::Xaml::Controls::RichTextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playMessage"));
    // Get the StackPanel named 'ButtonPanel'
    ButtonPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ButtonPanel"));
    // Get the Storyboard named 'playButtonTurn'
    playButtonTurn = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playButtonTurn"));
    // Get the RotateTransform named 'buttonRotate'
    buttonRotate = safe_cast<::Windows::UI::Xaml::Media::RotateTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buttonRotate"));
}

void ::MemoryTest::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->Loaded +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Page_Loaded);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 12:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 13:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 14:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 15:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 16:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 17:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 18:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 19:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 20:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 21:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 22:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 23:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 24:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 25:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Entered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Card_Exited);
        break;
    case 26:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 27:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 28:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 29:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 30:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 31:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 32:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 33:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 34:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 35:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 36:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 37:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 38:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 39:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 40:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 41:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 42:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 43:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 44:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 45:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 46:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 47:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 48:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 49:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 50:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 51:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 52:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 53:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 54:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 55:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 56:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 57:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 58:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 59:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 60:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 61:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 62:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 63:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 64:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 65:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 66:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 67:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 68:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 69:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 70:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 71:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 72:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 73:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 74:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 75:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 76:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 77:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 78:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 79:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 80:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 81:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 82:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 83:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 84:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 85:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 86:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 87:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 88:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 89:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 90:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 91:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 92:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 93:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 94:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 95:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 96:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 97:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 98:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 99:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 100:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 101:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 102:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 103:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 104:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 105:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 106:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 107:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 108:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 109:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 110:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 111:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 112:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 113:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 114:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 115:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 116:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 117:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 118:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 119:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 120:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Shape_Tapped);
        break;
    case 121:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Cardback_Tapped);
        break;
    case 122:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Start_Tapped);
        break;
    case 123:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::MemoryTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::Show_How_Tapped);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

