

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class RichTextBlock;
                ref class StackPanel;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                ref class RotateTransform;
            }
        }
    }
}

namespace MemoryTest
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ messageArea;
        private: ::Windows::UI::Xaml::Controls::Grid^ cardGrid;
        private: ::Windows::UI::Xaml::Controls::RichTextBlock^ winMessage;
        private: ::Windows::UI::Xaml::Controls::RichTextBlock^ playMessage;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ButtonPanel;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ playButtonTurn;
        private: ::Windows::UI::Xaml::Media::RotateTransform^ buttonRotate;
    };
}

