# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

exception_catcher:
	g++ -Wall -o exception_catcher -g exception_catcher.cc

clean:
	rm -rf $(CLEAN_TARGETS) exception_catcher
