[InstallSHIELD Silent]
Version=v3.00.00
File=Response File
[DlgOrder]
Dlg0=Welcome-0
Dlg1=SdLicense-0
Dlg2=AskDestPath-0
Dlg3=SdSelectFolder-0
Dlg4=SdStartCopy-0
Dlg5=SdFinish-0
Count=6
[Welcome-0]
Result=1
[SdLicense-0]
Result=1
[AskDestPath-0]
szPath=<WINSYSDISK>\Multithreading
Result=1
[SdSelectFolder-0]
Result=1
szFolder=Multithreading
[SdStartCopy-0]
Result=1
[SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
