# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

macro_example:
	g++ -Wall -o macro_example -g macro_example.cc

clean:
	rm -rf $(CLEAN_TARGETS) macro_example
