# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

signal_catcher:
	gcc -Wall -o signal_catcher -g signal_catcher.c

clean:
	rm -rf $(CLEAN_TARGETS) signal_catcher
