# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

break_template:
	g++ -Wall -o break_template -g break_template.cc

clean:
	rm -rf $(CLEAN_TARGETS) break_template
