# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka

include ../../Makefile.include

mem_alloc_bug:
	gcc -Wall -o mem_alloc_bug -g mem_alloc_bug.c

clean:
	rm -rf $(CLEAN_TARGETS) mem_alloc_bug
