@echo off
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\bc56\test\vc6\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\cw8\test\vc6\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\dmbeta\test\vc6\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\gcc32\test\vc6\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\icl7\test\vc6\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\bc56\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\cw8\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\dmbeta\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\gcc32\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\icl7\cppdynamic_test.exe
H:\Publishing\Books\ImpC++\Drafting\test\Part3\Chapter3.1\cppdynamic_test\vc6\test\vc6\cppdynamic_test.exe
